name: CI

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Create envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MYSQL_ROOT_PASSWORD: somepass
          envkey_MYSQL_DATABASE: games-qa-db
          envkey_MYSQL_TCP_PORT: 5434
          file_name: .env
        
      - name: Run build
        run: |
          docker-compose --file docker-compose.yml build
          
      - name: Run ESLint
        run: docker-compose --file docker-compose.yml run games-qa-api yarn lint
